spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: root

---
spring:
  profiles: eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      # 注册到 2和3
      defaultZone: http://root:root@localhost:8762/eureka/,http://root:root@localhost:8763/eureka/

---
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      # 注册到 1和3
      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8763/eureka/

---
spring:
  profiles: eureka3
server:
  port: 8763
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      # 注册到 1和2
      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8762/eureka/