spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: root

---
spring:
  profiles: eureka1
server:
  port: 8761   # 你第一台主机的端口
eureka:
  instance:
    hostname: localhost  # 配置你第一台主机的ip，这里是本地
  client:
    service-url:
      defaultZone: http://root:root@localhost:8762/eureka/   # 将自己注册到另一台服务器

---
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost  # 配置你第一台主机的ip，这里是本地
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/