server:
  port: 8761

spring:
  application:
    name: @pom.artifactId@
  security:          # 开启安全， 注意WebSecurityConfig配置类必不可少
    user:
      name: root
      password: root

eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: false
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: false
    service-url:
      defaultZone: http://root:root@127.0.0.1:8761/eureka/    # 注意此处 eureka不可少  最后的 "/" 可不加